fix: duplicate Trainee profiles for the same email issue
Health-Education-England/tis-trainee-details pull request #215
Opened 2022-06-13 10:14 UTC by DorisWongNHS

by filtering out invalid GMC or GDC profiles

Duplicate profile with the same email and their GMC and GDC numbers: https://healtheducationengland.sharepoint.com/:x:/s/TISys/EQWkau13QGdHkPYeZpu8exEBOdTyDAx3j7F_GahpssM7YA
- "unknown"
- "n/a"
- "delete*"
are the common invalid GMC/GDC values

Looking to confirm, is it even better to filter out all non-numeric values for GMC/GDC numbers?

TIS21-3094: To identify common trends on duplicate records. Investigate the issue with the same email address being used on multiple records.

2022-06-14 10:17 UTC, Judge40 requested changes
We only want to filter on valid GMC when there are multiple trainee profiles found. if we find only one then we should always use it.

2022-06-14 12:37 UTC, DorisWongNHS commented
> We only want to filter on valid GMC when there are multiple trainee profiles found. if we find only one then we should always use it.

Thanks, @Judge40 
Putting up different scenarios for clarification. It would be good to let me know if this looks good to you.
![image](https://user-images.githubusercontent.com/56677534/173578558-b6650d71-e907-49b9-87c7-272d18d3f610.png)

2022-06-14 15:01 UTC, Judge40 approved these changes

2022-06-15 08:04 UTC, ReubenRobertsHEE approved these changes
Looks good, thanks Doris!

2022-06-15 08:36 UTC, merged